"""add_is_admin_to_user

Revision ID: 6fa3c215256c
Revises: 35e8022402c9
Create Date: 2026-08-17 15:50:04.807666
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6fa3c215256c'
down_revision: str | None = '35e8022402c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###