"""Add confidence_score and discovery_evidence to contacts

Revision ID: 9cf8aca01b4f
Revises: 131b4cc7e373
Create Date: 2026-09-09 19:56:18.481139
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9cf8aca01b4f'
down_revision: str | None = '131b4cc7e373'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 1. Add columns as nullable
    op.add_column('contacts', sa.Column('confidence_score', sa.Integer(), nullable=True))
    op.add_column('contacts', sa.Column('discovery_evidence', sa.JSON(), nullable=True))

    # 2. Backfill existing rows
    op.execute("UPDATE contacts SET confidence_score = 0 WHERE confidence_score IS NULL")
    op.execute("UPDATE contacts SET discovery_evidence = '{}' WHERE discovery_evidence IS NULL")

    # 3. Enforce NOT NULL using batch_alter_table to support SQLite
    with op.batch_alter_table('contacts') as batch_op:
        batch_op.alter_column('confidence_score', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('discovery_evidence', existing_type=sa.JSON(), nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'discovery_evidence')
    op.drop_column('contacts', 'confidence_score')
    # ### end Alembic commands ###