"""Add confidence_score and discovery_evidence to contacts

Revision ID: 9cf8aca01b4f
Revises: 131b4cc7e373
Create Date: 2026-09-09 19:56:18.481139
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9cf8aca01b4f'
down_revision: str | None = '131b4cc7e373'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('confidence_score', sa.Integer(), server_default='0', nullable=False))
    op.add_column('contacts', sa.Column('discovery_evidence', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'discovery_evidence')
    op.drop_column('contacts', 'confidence_score')
    # ### end Alembic commands ###