"""add email scheduler fields

Revision ID: 9f72ff9f9480
Revises: 20260802_0004
Create Date: 2026-08-03 16:41:38.593030
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9f72ff9f9480'
down_revision: str | None = '20260802_0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('emails', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('emails', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('emails', sa.Column('task_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'task_id')
    op.drop_column('emails', 'error_message')
    op.drop_column('emails', 'started_at')
    op.drop_column('emails', 'scheduled_at')
    # ### end Alembic commands ###