"""Add user_id to company_intelligence

Revision ID: dae0b8e343fd
Revises: 6fa3c215256c
Create Date: 2026-09-04 12:14:44.601590
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'dae0b8e343fd'
down_revision: str | None = '6fa3c215256c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_intelligence', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_company_intelligence_user_id'), 'company_intelligence', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_company_intelligence_user_id_users'), 'company_intelligence', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_company_intelligence_user_id_users'), 'company_intelligence', type_='foreignkey')
    op.drop_index(op.f('ix_company_intelligence_user_id'), table_name='company_intelligence')
    op.drop_column('company_intelligence', 'user_id')
    # ### end Alembic commands ###